{% set name = "funsor" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 87c339ae517a993a853494fea8c977f6d3c963b9b08250c1eff421a5fae4fefc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - makefun
    - multipledispatch
    - numpy >=1.7
    - opt_einsum >=2.3.2
    - typing_extensions

test:
  imports:
    - funsor
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pyro-ppl/funsor
  summary: Funsor is a tensor-like library for functions and distributions.
  description: |
    Funsor is a tensor-like library for functions and distributions.
    See [Functional tensors for probabilistic programming](https://arxiv.org/abs/1910.10775) for a system description.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  doc_url: https://funsor.pyro.ai/en/stable/
  dev_url: https://github.com/pyro-ppl/funsor

extra:
  recipe-maintainers:
    - wckdouglas
